name: Publish merge against develop

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: windows-2022

    env:
      Solution_Name: HypnotoadPlugin

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Checkout Downloads
      uses: actions/checkout@v3
      with:
        repository: BardMusicPlayer/Downloads
        ssh-key: ${{ secrets.DEPLOY_KEY_DOWNLOADS }}
        path: .\Downloads

    - name: Update plugin repo json
      run: |
        echo -e "[" > ./Downloads/hypnotoad/index.html
        cat ./HypnotoadPlugin/bin/x64/Release/HypnotoadPlugin/HypnotoadPlugin.json | sed '$d' >> ./Downloads/hypnotoad/index.html
        echo ",\"LoadPriority\": 0,\"IconUrl\": \"https://dl.bardmusicplayer.com/hypnotoad/icon.png\",\"IsHide\": \"False\",\"IsTestingExclusive\": \"False\",\"DownloadCount\": 0,\"LastUpdate\": \"`date +%s`\",\"DownloadLinkInstall\": \"https://dl.bardmusicplayer.com/hypnotoad/latest.zip\",\"DownloadLinkTesting\": \"https://dl.bardmusicplayer.com/hypnotoad/latest.zip\",\"DownloadLinkUpdate\": \"https://dl.bardmusicplayer.com/hypnotoad/latest.zip\"}]" >> ./Downloads/hypnotoad/index.html
      
    - name: Commit Downloads
      shell: bash
      working-directory: .\Downloads
      run: |
        git config --global user.email "doot@bardmusicplayer.com"
        git config --global user.name "Bard Build Bot"
        git add hypnotoad/*
        git commit -am"HypnotoadPlugin build ${{ github.run_number }} commit ${{ github.sha }}"
        git push origin HEAD
